# DOCKER_BUILDKIT=0 docker build -t carlosedp/golang:1.13-riscv64 -f Dockerfile.golang .

FROM carlosedp/debian:sid-slim-riscv64

ENV GOLANG_VERSION 1.13beta1

ADD go-1.13dev-riscv64.tar /usr/local/go

RUN export PATH="/usr/local/go/bin:$PATH"; \
    go version

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH
